'use client'

import Link from 'next/link'
import { Bell, CalendarDays, KeyRound, Settings, ShieldCheck } from 'lucide-react'
import { MobileShell } from '@/components/mobile-shell'

export default function ProfilePage() {
  return <MobileShell title="Profile"><main className="mx-auto max-w-xl px-4 pb-32 pt-8"><section className="rounded-[24px] border border-[#e9e2d9] bg-white p-6"><div className="flex items-center gap-4"><div className="flex size-16 items-center justify-center rounded-full bg-[#dce9dd] text-2xl font-semibold text-[#173f35]">R</div><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#c36d4d]">Your account</p><h1 className="mt-1 text-2xl font-semibold">Your profile</h1><p className="mt-1 text-sm text-[#68756e]">Manage your account and activity.</p></div></div><div className="mt-6 flex items-start gap-3 rounded-2xl bg-[#edf4ee] p-4"><ShieldCheck className="mt-0.5 size-5 shrink-0 text-[#4e8068]" /><p className="text-sm leading-6 text-[#52665a]">Keep your information private and use the platform safely.</p></div></section><div className="mt-5 grid gap-3 sm:grid-cols-2"><Link href="/dashboard" className="rounded-2xl border border-[#e9e2d9] bg-white p-4"><CalendarDays className="size-5 text-[#c36d4d]" /><p className="mt-4 font-semibold">My bookings</p><p className="mt-1 text-sm text-[#68756e]">View your upcoming plans.</p></Link><Link href="/change-password" className="rounded-2xl border border-[#e9e2d9] bg-white p-4"><KeyRound className="size-5 text-[#c36d4d]" /><p className="mt-4 font-semibold">Change password</p><p className="mt-1 text-sm text-[#68756e]">Update your sign-in password.</p></Link><Link href="/notifications" className="rounded-2xl border border-[#e9e2d9] bg-white p-4"><Bell className="size-5 text-[#c36d4d]" /><p className="mt-4 font-semibold">Notifications</p><p className="mt-1 text-sm text-[#68756e]">Stay up to date.</p></Link><Link href="/settings" className="rounded-2xl border border-[#e9e2d9] bg-white p-4"><Settings className="size-5 text-[#c36d4d]" /><p className="mt-4 font-semibold">Settings</p><p className="mt-1 text-sm text-[#68756e]">Privacy and account settings.</p></Link></div></main></MobileShell>
}
