'use client'

import Link from 'next/link'
import { useState } from 'react'
import { CheckCircle2 } from 'lucide-react'

export default function RegisterPage() {
  const [created, setCreated] = useState(false)
  return <main className="flex min-h-screen items-center justify-center bg-[#fbfaf7] px-4 py-10"><div className="w-full max-w-md rounded-3xl border border-[#e9e2d9] bg-white p-6 shadow-sm sm:p-8"><Link href="/" className="text-lg font-semibold text-[#173f35]">rent<span className="text-[#d17b58]">gf</span></Link><h1 className="mt-10 text-3xl font-semibold tracking-[-.04em] text-[#173f35]">Create your account</h1><p className="mt-2 text-sm leading-6 text-[#68756e]">Join adults 18+ seeking lawful, non-sexual companionship.</p>{created ? <div className="mt-8 rounded-2xl border border-[#cfe2d3] bg-[#f4faf4] p-5"><CheckCircle2 className="size-6 text-[#4e8068]" /><p className="mt-3 font-semibold">Account created in preview</p><p className="mt-1 text-sm leading-6 text-[#68756e]">Real account creation will activate after authentication is connected.</p><Link href="/login" className="mt-4 inline-flex rounded-xl bg-[#173f35] px-4 py-3 text-sm font-semibold text-white">Continue to login</Link></div> : <form onSubmit={(event) => { event.preventDefault(); setCreated(true) }} className="mt-8 flex flex-col gap-4"><label className="text-sm font-medium">Display name<input required className="mt-2 w-full rounded-xl border border-[#e5e1da] px-3 py-3 outline-none focus:ring-2 focus:ring-[#bdd2c7]" /></label><label className="text-sm font-medium">Email<input type="email" required className="mt-2 w-full rounded-xl border border-[#e5e1da] px-3 py-3 outline-none focus:ring-2 focus:ring-[#bdd2c7]" /></label><label className="text-sm font-medium">Password<input type="password" minLength={8} required className="mt-2 w-full rounded-xl border border-[#e5e1da] px-3 py-3 outline-none focus:ring-2 focus:ring-[#bdd2c7]" /></label><label className="text-sm font-medium">Date of birth<input type="date" required className="mt-2 w-full rounded-xl border border-[#e5e1da] px-3 py-3 outline-none focus:ring-2 focus:ring-[#bdd2c7]" /></label><label className="flex gap-3 text-sm text-[#68756e]"><input type="checkbox" required className="mt-1" /> I confirm I am 18 or older and agree to the non-sexual companionship policy.</label><button type="submit" className="rounded-xl bg-[#173f35] px-4 py-3 font-semibold text-white">Create account</button></form>}<p className="mt-6 text-sm text-[#68756e]">Already have an account? <Link href="/login" className="font-semibold text-[#c36d4d]">Log in</Link></p></div></main>
}
