import Link from 'next/link'
import { Bell, CalendarDays, Heart, MessageCircle, ShieldCheck } from 'lucide-react'
import { MobileShell } from '@/components/mobile-shell'
import { PreviewBookings } from '@/components/preview-bookings'
import { PreviewBanner } from '@/components/preview-banner'

const items = [['Upcoming bookings', 'No bookings yet. Your next plan can start here.', '/discover', 'Explore companions'], ['Likes', 'Like profiles you want to revisit.', '/likes', 'View liked profiles'], ['Messages', 'Conversations will appear here after a booking.', '/messages', 'Open messages']]

export default function DashboardPage() {
  return <MobileShell title="My bookings"><main className="mx-auto max-w-6xl px-4 py-8 sm:px-6"><PreviewBanner compact /><div className="mt-5"><PreviewBookings /></div><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-[#c36d4d]">Your space</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.05em]">Welcome to RentGF</h1><p className="mt-3 text-[#68756e]">Track your bookings, likes, and conversations.</p></div><Link href="/notifications" aria-label="Notifications" className="rounded-full border border-[#e4e9e1] bg-white p-3"><Bell className="size-5" /></Link></div><div className="mt-8 grid gap-4 sm:grid-cols-3">{[['Upcoming bookings', CalendarDays], ['Likes', Heart], ['Messages', MessageCircle]].map(([label, Icon]) => <div key={label as string} className="rounded-2xl border border-[#e9e2d9] bg-white p-5"><Icon className="size-5 text-[#c36d4d]" /><p className="mt-5 text-sm text-[#68756e]">{label as string}</p><p className="mt-1 text-2xl font-semibold">0</p></div>)}</div><div className="mt-8 grid gap-5 md:grid-cols-3">{items.map(([title, text, href, action]) => <section key={title} className="rounded-2xl border border-[#e9e2d9] bg-white p-5"><h2 className="font-semibold">{title}</h2><p className="mt-3 min-h-12 text-sm leading-6 text-[#68756e]">{text}</p><Link href={href} className="mt-5 inline-block text-sm font-semibold text-[#c36d4d]">{action} →</Link></section>)}</div><section className="mt-8 flex gap-4 rounded-2xl bg-[#edf4ee] p-5"><ShieldCheck className="size-5 shrink-0 text-[#4d8a73]" /><div><h2 className="font-semibold">Your safety comes first</h2><p className="mt-1 text-sm leading-6 text-[#68756e]">Keep conversations respectful, meet in public, and report anything that feels wrong.</p></div></section></main></MobileShell>
}
